In [1]:
import numpy as np

In [53]:
# 1

def vander_matrix(input_vect, N = None, increasing = False):
    
    if N == None:
        N = len(input_vect)
    if increasing == True:
        
        output = [[pow(i, power) for power in range(0, N)] for i in input_vect]
        print(np.asarray(output))
    else:
        output = [[pow(i, power) for power in range(N-1,-1,-1)] for i in input_vect]
        print(np.asarray(output))


input_vect = [1,2,3,5]  

In [54]:
vander_matrix(input_vect, increasing = True,N=4)

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


In [56]:
vander_matrix(input_vect)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [91]:
# 2

x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [92]:
len(x)

13

In [89]:
def mov_avg(x, window_size):
    for i in range(len(x)-(window_size-1)):
        yield sum(np.ones(window_size) * x[i:i + window_size]) / window_size

In [90]:
np.round(list(mov_avg(x,3)),1)

array([  5. ,   4.7,   5.7,   6.7,   9.7,  28.7,  49.3,  72.7,  84. ,
        93.3, 116.3])